version: '3.8'

services:
  api:
    build: .
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - DEV_MODE=${DEV_MODE:-development}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EXCHANGE_API_KEY=${EXCHANGE_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    depends_on:
      - redis
    volumes:
      - ./app:/app/app

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  redis_data:
