name: Docker Deploy Pipeline

on:
    push:
        branches:
            - main
    workflow_run:
        workflows: ["Linting Pipeline"]
        types:
            - completed

jobs:
    docker_deploy:
        name: Docker build and deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Docker Build
              uses: docker/setup-buildx-action@v2

            - name: Install Docker Compose
              run: |
                sudo apt-get update
                sudo apt-get install -y docker-compose

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Docker Image
              run: |
                docker-compose -f docker-compose.yml build
                docker tag currency-converter-api:latest ${{ secrets.DOCKER_USERNAME}}/currency-converter-api:latest
                docker push ${{ secrets.DOCKER_USERNAME}}/currency-converter-api:latest

            - name: Deploy with Docker Compose
              run: |
                docker-compose -f docker-compose.yml up -d
